### ISSUE TITLE
Error: Build faield

### ISSUE THREAD

**Issue by nikunjazilen** [AdactiveSAS/adsum-example-ios-basicdemo#1]
Hi,

I am facing the build error in simulator but its working device. Can you please help me to solve the below error in simulator? Xcode 8.2 

```
"_OBJC_CLASS_$_ADSumMapViewController", referenced from:
      objc-class-ref in AdsumMapViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Best Regards,
Nikunj

**Comment by oursodon** [comment]
Hey,

We don't support the emulator at the moment.
You'll have to use a real device.

Regards,
Quentin

**Comment by nikunjazilen** [comment]
Ok. Thanks for the reply.
